// Mock data para desarrollo sin base de datos

export const mockProducts = [
  {
    id: '1',
    name: 'iPhone 15 Pro Max',
    slug: 'iphone-15-pro-max',
    description: 'El último iPhone con chip A17 Pro y cámara de 48MP',
    price: 1199.99,
    compareAtPrice: 1299.99,
    stock: 50,
    sku: 'IPH15PM-256-BLU',
    isFeatured: true,
    isActive: true,
    rating: 4.8,
    reviewCount: 245,
    brand: {
      id: '1',
      name: 'Apple',
      slug: 'apple',
      logo: 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=100',
    },
    category: {
      id: '1',
      name: 'Smartphones',
      slug: 'smartphones',
    },
    images: [
      {
        id: '1',
        url: 'https://images.unsplash.com/photo-1678685888221-cda773a3dcdb?w=800',
        alt: 'iPhone 15 Pro Max',
        order: 0,
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Samsung Galaxy S24 Ultra',
    slug: 'samsung-galaxy-s24-ultra',
    description: 'Potente smartphone con S Pen y cámara de 200MP',
    price: 1099.99,
    compareAtPrice: null,
    stock: 35,
    sku: 'SAM-S24U-512-BLK',
    isFeatured: true,
    isActive: true,
    rating: 4.7,
    reviewCount: 189,
    brand: {
      id: '2',
      name: 'Samsung',
      slug: 'samsung',
      logo: 'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=100',
    },
    category: {
      id: '1',
      name: 'Smartphones',
      slug: 'smartphones',
    },
    images: [
      {
        id: '2',
        url: 'https://images.unsplash.com/photo-1610945264803-c22b62d2a7b6?w=800',
        alt: 'Samsung Galaxy S24 Ultra',
        order: 0,
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'MacBook Pro 16" M3 Max',
    slug: 'macbook-pro-16-m3-max',
    description:
      'Portátil profesional con chip M3 Max y pantalla Liquid Retina XDR',
    price: 2499.99,
    compareAtPrice: 2699.99,
    stock: 20,
    sku: 'MBP16-M3M-1TB-SG',
    isFeatured: true,
    isActive: true,
    rating: 4.9,
    reviewCount: 312,
    brand: {
      id: '1',
      name: 'Apple',
      slug: 'apple',
      logo: 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=100',
    },
    category: {
      id: '2',
      name: 'Laptops',
      slug: 'laptops',
    },
    images: [
      {
        id: '3',
        url: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800',
        alt: 'MacBook Pro 16"',
        order: 0,
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Sony WH-1000XM5',
    slug: 'sony-wh-1000xm5',
    description:
      'Auriculares premium con cancelación de ruido líder en la industria',
    price: 399.99,
    compareAtPrice: null,
    stock: 75,
    sku: 'SONY-WH1000XM5-BLK',
    isFeatured: true,
    isActive: true,
    rating: 4.8,
    reviewCount: 567,
    brand: {
      id: '3',
      name: 'Sony',
      slug: 'sony',
      logo: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=100',
    },
    category: {
      id: '3',
      name: 'Auriculares',
      slug: 'auriculares',
    },
    images: [
      {
        id: '4',
        url: 'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=800',
        alt: 'Sony WH-1000XM5',
        order: 0,
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'iPad Air M2',
    slug: 'ipad-air-m2',
    description: 'Tablet potente con chip M2 y pantalla Liquid Retina',
    price: 599.99,
    compareAtPrice: null,
    stock: 45,
    sku: 'IPAD-AIR-M2-256-BLU',
    isFeatured: true,
    isActive: true,
    rating: 4.7,
    reviewCount: 223,
    brand: {
      id: '1',
      name: 'Apple',
      slug: 'apple',
      logo: 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=100',
    },
    category: {
      id: '4',
      name: 'Tablets',
      slug: 'tablets',
    },
    images: [
      {
        id: '5',
        url: 'https://images.unsplash.com/photo-1585790050230-5dd28404ccb9?w=800',
        alt: 'iPad Air M2',
        order: 0,
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Dell XPS 15',
    slug: 'dell-xps-15',
    description:
      'Portátil premium con pantalla OLED 4K y procesador Intel Core i9',
    price: 1899.99,
    compareAtPrice: 2099.99,
    stock: 15,
    sku: 'DELL-XPS15-1TB-PLT',
    isFeatured: true,
    isActive: true,
    rating: 4.6,
    reviewCount: 178,
    brand: {
      id: '4',
      name: 'Dell',
      slug: 'dell',
      logo: 'https://images.unsplash.com/photo-1593642532454-e138e28a63f4?w=100',
    },
    category: {
      id: '2',
      name: 'Laptops',
      slug: 'laptops',
    },
    images: [
      {
        id: '6',
        url: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=800',
        alt: 'Dell XPS 15',
        order: 0,
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const mockCategories = [
  {
    id: '1',
    name: 'Smartphones',
    slug: 'smartphones',
    description: 'Los últimos smartphones del mercado',
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400',
    icon: 'Smartphone',
    isActive: true,
    order: 1,
    parentId: null,
    _count: { products: 45 },
  },
  {
    id: '2',
    name: 'Laptops',
    slug: 'laptops',
    description: 'Portátiles para trabajo y gaming',
    image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400',
    icon: 'Laptop',
    isActive: true,
    order: 2,
    parentId: null,
    _count: { products: 38 },
  },
  {
    id: '3',
    name: 'Auriculares',
    slug: 'auriculares',
    description: 'Audio de alta calidad',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400',
    icon: 'Headphones',
    isActive: true,
    order: 3,
    parentId: null,
    _count: { products: 62 },
  },
  {
    id: '4',
    name: 'Tablets',
    slug: 'tablets',
    description: 'Tablets para trabajo y entretenimiento',
    image: 'https://images.unsplash.com/photo-1585790050230-5dd28404ccb9?w=400',
    icon: 'Tablet',
    isActive: true,
    order: 4,
    parentId: null,
    _count: { products: 28 },
  },
  {
    id: '5',
    name: 'Smart Home',
    slug: 'smart-home',
    description: 'Dispositivos inteligentes para tu hogar',
    image: 'https://images.unsplash.com/photo-1558089687-e18a785d41f5?w=400',
    icon: 'Home',
    isActive: true,
    order: 5,
    parentId: null,
    _count: { products: 51 },
  },
  {
    id: '6',
    name: 'Accesorios',
    slug: 'accesorios',
    description: 'Todo tipo de accesorios tecnológicos',
    image: 'https://images.unsplash.com/photo-1550009158-9ebf69173e03?w=400',
    icon: 'Cable',
    isActive: true,
    order: 6,
    parentId: null,
    _count: { products: 124 },
  },
];
